### ISSUE TITLE
expose X11 display from the docker container

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/SciGraph-docker-monarch-data#1]
ERROR [2016-02-03 23:14:00,620] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 7aa6dd290feef914
! java.awt.HeadlessException: 
! No X11 DISPLAY variable was set, but this program performed an operation which requires it.
! at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204) ~[na:1.8.0_72]
! at java.awt.Window.<init>(Window.java:536) ~[na:1.8.0_72]
! at java.awt.Frame.<init>(Frame.java:420) ~[na:1.8.0_72]
! at java.awt.Frame.<init>(Frame.java:385) ~[na:1.8.0_72]
! at javax.swing.JFrame.<init>(JFrame.java:189) ~[na:1.8.0_72]
! at io.scigraph.services.jersey.writers.ImageWriter.renderImage(ImageWriter.java:155) ~[scigraph-services-1.5-SNAPSHOT.jar:na]
! at io.scigraph.services.jersey.writers.ImageWriter.writeTo(ImageWriter.java:184) ~[scigraph-services-1.5-SNAPSHOT.jar:na]
! at io.scigraph.services.jersey.writers.ImageWriter.writeTo(ImageWriter.java:64) ~[scigraph-services-1.5-SNAPSHOT.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:265) ~[org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:250) ~[org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.server.internal.JsonWithPaddingInterceptor.aroundWriteTo(JsonWithPaddingInterceptor.java:106) ~[org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.server.internal.MappableExceptionWrapperInterceptor.aroundWriteTo(MappableExceptionWrapperInterceptor.java:86) ~[org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:162) ~[org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1128) ~[org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.writeResponse(ServerRuntime.java:664) ~[org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.processResponse(ServerRuntime.java:421) ~[org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$Responder.process(ServerRuntime.java:411) ~[org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:308) ~[org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [org.glassfish.jersey.core.jersey-common-2.17.jar:na]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:288) [org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1110) [org.glassfish.jersey.core.jersey-server-2.17.jar:na]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:401) [org.glassfish.jersey.containers.jersey-container-servlet-core-2.17.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [org.glassfish.jersey.containers.jersey-container-servlet-core-2.17.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:335) [org.glassfish.jersey.containers.jersey-container-servlet-core-2.17.jar:na]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:222) [org.glassfish.jersey.containers.jersey-container-servlet-core-2.17.jar:na]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [io.dropwizard.dropwizard-jetty-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [org.eclipse.jetty.jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:315) [org.eclipse.jetty.jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [io.dropwizard.dropwizard-jetty-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.servlets.ThreadNameFilter.doFilter(ThreadNameFilter.java:29) [io.dropwizard.dropwizard-servlets-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.handle(AllowedMethodsFilter.java:44) [io.dropwizard.dropwizard-jersey-0.8.1.jar:0.8.1]
! at io.dropwizard.jersey.filter.AllowedMethodsFilter.doFilter(AllowedMethodsFilter.java:39) [io.dropwizard.dropwizard-jersey-0.8.1.jar:0.8.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:259) [org.eclipse.jetty.jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:222) [org.eclipse.jetty.jetty-servlets-9.2.9.v20150224.jar:9.2.9.v20150224]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:89) [com.google.inject.extensions.guice-servlet-4.0.jar:na]
! at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:119) [com.google.inject.extensions.guice-servlet-4.0.jar:na]
! at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:133) [com.google.inject.extensions.guice-servlet-4.0.jar:na]
! at com.google.inject.servlet.GuiceFilter$1.call(GuiceFilter.java:130) [com.google.inject.extensions.guice-servlet-4.0.jar:na]
! at com.google.inject.servlet.GuiceFilter$Context.call(GuiceFilter.java:203) [com.google.inject.extensions.guice-servlet-4.0.jar:na]
! at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:130) [com.google.inject.extensions.guice-servlet-4.0.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9.v20150224]
! at io.scigraph.services.swagger.SwaggerDocUrlFilter.doFilter(SwaggerDocUrlFilter.java:46) [scigraph-services-1.5-SNAPSHOT.jar:na]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [org.eclipse.jetty.jetty-servlet-9.2.9.v20150224.jar:9.2.9..

**Comment by kltm** [comment]
Maybe add xvfb and get it running upfront?

**Comment by jnguyenx** [comment]
Yeah there are some options, here's one:

http://stackoverflow.com/questions/16296753/can-you-run-gui-apps-in-a-docker-container

**Comment by kltm** [comment]
VNC is a bit icky, no? And I assume it would be bringing X in anyways.

**Comment by jnguyenx** [comment]
So I just included xvfb in the docker image, but on the server itself more package needed to be installed. I added that in the ansible scripts.

Note that before starting the docker image, we need to export a DISPLAY environment variable and start a xfvb process.

xvfb :1 -screen 0 800x600x16

export DISPLAY=:1
