### ISSUE TITLE
Add versionInfo property to Ontology nodes

### ISSUE THREAD

**Issue by kshefchek** [monarch-initiative/SciGraph-docker-monarch-data#3]
Can this be added to the mappedProperties in the yaml?

Then we can get the date that each ontology and data source was ingested in our graph.

```
    - name: version
        properties:
        - http://www.w3.org/2002/07/owl#versionInfo
```

**Comment by kshefchek** [comment]
This looks like it should work I still don't see the node properties, for example:
https://scigraph-data-dev.monarchinitiative.org/scigraph/graph/MonarchData%3Aanimalqtldb.ttl?project=*

In the ttl file:

    MonarchData:animalqtldb.ttl a owl:Ontology ;
        owl:versionIRI <https://archive.monarchinitiative.org/201702/ttl/animalqtldb.ttl> ;
        owl:versionInfo "animalqtldb-201703" .

**Comment by cmungall** [comment]
Looks like versionIRI has never been populated:

https://github.com/SciGraph/SciGraph/blob/5d6ed03b2c45c68cbe16fd205cde823f6672cef6/SciGraph-core/src/main/java/io/scigraph/owlapi/GraphOwlVisitor.java#L118-L129

This should be extended, call getVersionIRI() on the OWLOntologyID object, make either a node or property from it? (probably node? what do you think?)

First thing to do is to add a test case here:
https://github.com/SciGraph/SciGraph/tree/master/SciGraph-core/src/test/resources/ontologies/cases
