### ISSUE TITLE
Cycle in the graph

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/SciGraph-docker-monarch-data#4]
![graph](https://cloud.githubusercontent.com/assets/4312088/22043705/c6363ae8-dcc5-11e6-85ed-bb3a659010c4.png)
```
http://purl.obolibrary.org/obo/DOID_1242 (globe disease)
http://purl.obolibrary.org/obo/DOID_5614 (eye disease)
```

I tracked down the backward edge in http://purl.obolibrary.org/obo/clo.owl.
```
    <!-- http://purl.obolibrary.org/obo/DOID_5614 -->

    <owl:Class rdf:about="&obo;DOID_5614">
        <rdfs:label rdf:datatype="&xsd;string">eye disease</rdfs:label>
        <rdfs:subClassOf rdf:resource="&obo;DOID_1242"/>
```

@cmungall @mbrush @kshefchek

**Comment by jnguyenx** [comment]
I found another cycle, coming from clo.owl again. This time it's a 2 hops cycle:
![graph 1](https://cloud.githubusercontent.com/assets/4312088/22080601/057b2114-dd75-11e6-9598-192f42854239.png)
The false assertion is:
`(http://purl.obolibrary.org/obo/DOID_308)-[:subClassOf]->(http://purl.obolibrary.org/obo/OMIM_545000)`

**Comment by cmungall** [comment]
can we move this to dipper?

**Comment by jnguyenx** [comment]
https://github.com/monarch-initiative/dipper/issues/409
